### ISSUE TITLE
Use of optim tools/API/lib/algo

### ISSUE THREAD

**Issue by alkaphreak** [memeller/shrunked#17]
Can we an option to be able to use external lib, tools or API like : 

- https://imagecompressor.com/fr/
- https://imageoptim.com/mac
- https://tinypng.com/
- https://github.com/Lymphatus/libcaesium

Often the image we send are poorly optimized even after a resize.

**Comment by alkaphreak** [comment]
An other one i'm lookingt at : https://github.com/thumbor/thumbor

**Comment by memeller** [comment]
This is very unlikely to be implemented.

An external service means delays, timeouts, server responses, server errors, all of which need to be handled by the UI. Then there is the issue of API keys, free tiers and paid services.

Also if you look at the services mentioned:
- Imagecompressor does not have an open api,
- Thumbor requires a separate http server running in the background,
- Imageoptim is a paid web service,
- TinyPNG has a free tier, but after that it becomes a paid service,
- Liibcaesium is written in Rust with a C interface and trying to integrate it into a web extension might be compelling for some Rust developers, but unfortunately I am not a Rust developer.

It  might be doable to add a different JS based algorithm (we currently have two available). 

You can also upload the images that give 'poorly optimised' results and maybe someone will be able to figure out what the problem is and fix it.

**Comment by alkaphreak** [comment]
I'm sorry, i've made some tries since your reply and you are right, your optim is better than me resizing on my side and testing using two types of optim.

Yours is better in weight (the better the lesser) but the picture is not as good in visual quality.

But these are implem choices i guess :)

Here is my two test, if you are curious. The first one, is an imagemagick resized pic, followed by imagecompressor optim. The second one, is a pic sent by mail with your plugin to resize and optim.

![imagecompressor](https://github.com/memeller/shrunked/assets/4222406/0b04254e-a3af-45c9-8275-17697ba9c44a)

![tbird-shrunked](https://github.com/memeller/shrunked/assets/4222406/579eec54-2472-4089-b94b-a1b3400670e9)

**Comment by memeller** [comment]
Unfortunately since we rely on rather simple javascript and are limited by Thunderbird add-on rules, it will not be possible to achieve the quality and size offered by specialized larger tools e.g. imagemagick.
