### ISSUE TITLE
[BUG] not working with TB beta 131.0b4

### ISSUE THREAD

**Issue by moreje** [memeller/shrunked#34]
**Describe the bug**
the addon has no action, no error when used with TB 131.0b4

**To Reproduce**
use the addon with beta release of TB

**Expected behavior**
addon activation when adding a big image

**Screenshots**

**Desktop (please complete the following information):**
1. Win 11
2. Thunderbird version, 131.0b4
3. Extension version, 5.7.1
4. Image details - format, size,: JPG 4Mo
5. Extension settings,
6. If you are having issues with manual resizing: 
- Is the notification displayed when image is attached : NO
- Is the notification displayed when image is inserted inline : NO
- Is there an option to resize the image when right clicking on attached / inline images: NO
7. Did this feature work in previous versions: in orevious TB versions, YES

**Additional context**
Add any other context about the problem here. Please add e.g. debug log (Tools -> Developer Tools -> Error console)

**Comment by memeller** [comment]
Support for beta releases is limited.
Mozilla does not provide update information for beta releases ([should be provided here](https://developer.thunderbird.net/add-ons/updating)), so it is difficult to track what exactly has changed and whether the reason for a particular behavior is due to a bug that will be fixed in the next release, or if it is due to a change in the extension system (as with ESMification).

**Comment by memeller** [comment]
So I've just checked 131.0b6 and the extension works... if you update to the [latest version](https://github.com/memeller/shrunked/releases/) (3.8.2).
